# Generated by Django 4.0.4 on 2022-04-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='aviable',
            new_name='available',
        ),
    ]
