# Generated by Django 4.0.4 on 2022-05-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(max_length=50, verbose_name='Şərh Yazarı'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=200, verbose_name='Şərh'),
        ),
    ]
