# Generated by Django 4.0.4 on 2022-05-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_course_price_alter_comment_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.CharField(max_length=3),
        ),
    ]
